# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 15e8d66cc510e48f89db27da1ea831c26d3637b4fb43ef4c9fec660f044b191e79b779e8a640dff073531304b9db7eb438fa392a44c894c8ddfc8dffd78ae634

test:
  secret_key_base: d3abbcae16a2ddf24c57d3207c58b17ec82c5b527400a9605c535c738bbd2d08628f84c09412aaea27b66da673c1980de78dcbd3e2d9aab61554314f7c8d4bc1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
